### PR TITLE
Switch from Nose to unittest

### PR DESCRIPTION
**Pull request by koterpillar**
See https://github.com/aloetesting/aloe/pull/117.

### CODE REVIEW

**Review by danni — APPROVED** [review]

**Comment by jricardo27** [comment]
Hi Alexy, I tried this branch but it fails when using `ManifestStaticFilesStorage`.

I setup a dummy project ( https://github.com/jricardo27/channels_example/pull/12 ) and a simple test:
- Python 3.5
- Django 1.11.0
- Test check for "Hello World" to appear on page.
- Home page imports a static file.

I'm using a fork of this branch; I had to remove `--e git+https://github.com/aloetesting/aloe.git@2ea3e68a77fe93884407295b1498a36f8e5c56bc#egg=aloe` from `requirements.txt` as it made it fail when trying to install the package.
```
  Cloning https://github.com/aloetesting/aloe_django (to 42ab35fa91173cb08247b0fe1ef42cfd3c326471) to /private/var/folders/rj/gxjbdbbd19g2576rxfl2tpy80000gp/T/pip-build-mq1rpc4p/aloe-django
  Could not find a tag or branch '42ab35fa91173cb08247b0fe1ef42cfd3c326471', assuming commit.
    Complete output from command python setup.py egg_info:
    error in aloe_django setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'-e git+h'"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rj/gxjbdbbd19g2576rxfl2tpy80000gp/T/pip-build-mq1rpc4p/aloe-django/
```

\-------------

From what I see, it seems like overriding `DEBUG` is not taking effect.
```
from aloe_django import TestCase as AloeTestCase

@override_settings(DEBUG=True)
class TestCase(AloeTestCase):
    pass
```

But it works with the old `aloe`.

**Comment by jricardo27** [comment]
I fixed it with https://github.com/jricardo27/aloe_django/commit/3dd8800c3d8fc3d42dd692455e249beb8693bb9a

**Comment by koterpillar** [comment]
Hi Ricardo!

Glad to hear you're trying this. I'd be very interested in hearing about the results of running the pure unittest branch on a large codebase.

I've applied a patch inspired by your change - `aloe` already has an analog for `locate`.

The `requirements.txt` problem is because the branch is still experimental, so you'd have to install `aloe` manually.

**Comment by jricardo27** [comment]
I plugged it in one of my projects, so far seems to be working ok, I'll tell you how it finish as it takes a couple of hours to run.


\------
I started using this branch because I'm running into a problem when using `Django Channels` the first test runs ok but the following ones fail due to DB disconnected.

I already open an issue in their project and they couldn't find anything (https://github.com/django/channels/issues/614); they recommended to stop using `nose` and/or ask for help in here.

I just saw there is a new issue with the same problem but it doesn't use `aloe` (https://github.com/django/channels/issues/616), so I guess the problem has to do with Django's test framework.

Any idea where can I start looking, I'm pretty at a loss in how all the test framework is knit together.

I have this pet project to test `channels` + `aloe` in case you feel like taking a look (https://github.com/jricardo27/channels_example/pull/13)

The traceback is:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
psycopg2.DatabaseError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/testcases.py", line 216, in __call__
    self._post_teardown()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/channels/test/liveserver.py", line 224, in _post_teardown
    super(ChannelLiveServerTestCase, self)._post_teardown()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/testcases.py", line 925, in _post_teardown
    self._fixture_teardown()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/testcases.py", line 960, in _fixture_teardown
    inhibit_post_migrate=inhibit_post_migrate)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/commands/flush.py", line 54, in handle
    allow_cascade=allow_cascade)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/sql.py", line 15, in sql_flush
    tables = connection.introspection.django_table_names(only_existing=True, include_views=False)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/base/introspection.py", line 86, in django_table_names
    existing_tables = self.table_names(include_views=include_views)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/base/introspection.py", line 54, in table_names
    return get_names(cursor)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/base/introspection.py", line 50, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/postgresql/introspection.py", line 67, in get_table_list
    AND pg_catalog.pg_table_is_visible(c.oid)""")
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 63, in execute
    return self.cursor.execute(sql)
django.db.utils.DatabaseError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by koterpillar** [comment]
I see that `channels` override `TestCase` as well. All those class are fragile at best - Aloe, Nose and Django all hook into them in special, sometimes unsupported ways. Unfortunately, even going to plain `unittest` wasn't enough to get rid of all the magic, so I think the best way would be to look at what `channels` is doing and work around that.

**Comment by jricardo27** [comment]
Thanks for that, I focused on `channels` and I think I found a solution, not sure why it works though...

\------
My battery of tests is still running (around 5 hours so far). I saw some tests failing but probably they have been already broken before upgrading `aloe`.

**Comment by danni** [comment]
I was reasonably comfortably able to mix Channel's `TestCase` into nose, but I haven't tried with Aloe yet (all of my Channels tests are unit tests).

**Comment by jricardo27** [comment]
It seems that the test run was ok (failed tests were already broken).

However I noticed that I had this defined:
```
TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'
```

I removed it and ran a couple of tests again and they were ok.

Also noticed I have some of these `from nose.tools import assert_true` around, I guess it doesn't matter.

**Comment by koterpillar** [comment]
Uncluttering my PRs.

**Pull request closed without merging**
